CREATE DATABASE PI_FLOW;

CREATE SCHEMA PI_FLOW.METADATA;

USE DATABASE PI_FLOW;
USE SCHEMA METADATA;


SELECT CURRENT_ACCOUNT(), CURRENT_REGION();

SHOW WAREHOUSES;
--------------------
-- Tables
--------------------

CREATE OR REPLACE TABLE DAG (
    dag_id STRING PRIMARY KEY,
    fileloc STRING,
    schedule_interval STRING,
    is_paused BOOLEAN,
    owners STRING,
    description STRING,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    tags STRING,
    PARAMS_SCHEMA VARIANT
);

CREATE OR REPLACE TABLE PI_FLOW.METADATA.DAG_FILE (
    FILE_PATH VARCHAR NOT NULL,
    DAG_ID VARCHAR NOT NULL,
    FILE_HASH VARCHAR NOT NULL,
    LAST_PARSED_AT TIMESTAMP_NTZ,
    PRIMARY KEY (FILE_PATH),
    CONSTRAINT FK_DAG_FILE_DAG
      FOREIGN KEY (DAG_ID)
      REFERENCES PI_FLOW.METADATA.DAG(DAG_ID)
);

CREATE OR REPLACE TABLE DAG_RUN (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    dag_id STRING,
    run_id STRING,
    state STRING,
    execution_date TIMESTAMP,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    run_type STRING,
    CONF VARIANT,
    -- logical reference
    CONSTRAINT fk_dagrun_dag
        FOREIGN KEY (dag_id) REFERENCES DAG(dag_id)
);

ALTER TABLE DAG_RUN
ADD COLUMN TASKS_CREATED BOOLEAN DEFAULT FALSE;

ALTER TABLE PI_FLOW.METADATA.DAG_RUN
ADD CONSTRAINT UNIQUE_DAG_RUN UNIQUE (DAG_ID, RUN_ID);



CREATE TABLE TASK_INSTANCE (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    dag_id STRING,
    task_id STRING,
    run_id STRING,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    state STRING,
    try_number INTEGER,
    operator STRING,
    duration FLOAT,
    hostname STRING,
    log_filepath STRING,

    -- references DAG + DAG_RUN
    CONSTRAINT fk_ti_dag
        FOREIGN KEY (dag_id) REFERENCES DAG(dag_id)
);

ALTER TABLE PI_FLOW.METADATA.TASK_INSTANCE
ADD COLUMN NEXT_RETRY_AT TIMESTAMP_NTZ(9);

CREATE TABLE JOB (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    dag_id STRING,
    state STRING,
    job_type STRING,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    hostname STRING,

    CONSTRAINT fk_job_dag
        FOREIGN KEY (dag_id) REFERENCES DAG(dag_id)
);

ALTER TABLE JOB ADD COLUMN run_id STRING;

ALTER TABLE JOB 
ADD COLUMN latest_heartbeat TIMESTAMP,
 COLUMN executor_class STRING;



CREATE TABLE LOG (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    dag_id STRING,
    task_id STRING,
    run_id STRING,
    try_number INTEGER,
    event STRING,
    when TIMESTAMP,
    message STRING
);

CREATE TABLE VARIABLE (
    key STRING PRIMARY KEY,
    value STRING
);

CREATE TABLE CONNECTION (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    conn_id STRING UNIQUE,
    conn_type STRING,
    host STRING,
    schema STRING,
    login STRING,
    password STRING,
    port INTEGER,
    extra STRING
);

CREATE OR REPLACE TABLE PI_FLOW.METADATA.TASK (
    ID NUMBER(38,0)
        AUTOINCREMENT START 1000 INCREMENT 1 NOORDER,
    DAG_ID VARCHAR NOT NULL,
    TASK_ID VARCHAR NOT NULL,
    OPERATOR VARCHAR,
    OWNER VARCHAR,
    DESCRIPTION VARCHAR,
    RETRIES NUMBER DEFAULT 0,
    RETRY_DELAY_SECONDS NUMBER,
    PARAMS VARIANT,
    CONSTRAINT UK_TASK UNIQUE (DAG_ID, TASK_ID),
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_DAG
        FOREIGN KEY (DAG_ID)
        REFERENCES PI_FLOW.METADATA.DAG(DAG_ID)
);

ALTER TABLE PI_FLOW.METADATA.TASK 
ADD COLUMN TRIGGER_RULE VARCHAR DEFAULT 'all_success';


CREATE OR REPLACE TABLE PI_FLOW.METADATA.TASK_DEPENDENCY (
    ID NUMBER(38,0)
        AUTOINCREMENT START 1000 INCREMENT 1 NOORDER,
    DAG_ID VARCHAR NOT NULL,
    UPSTREAM_TASK_ID VARCHAR NOT NULL,
    DOWNSTREAM_TASK_ID VARCHAR NOT NULL,
    CONSTRAINT UK_TASK_DEP
        UNIQUE (DAG_ID, UPSTREAM_TASK_ID, DOWNSTREAM_TASK_ID),
    PRIMARY KEY (ID),
    CONSTRAINT FK_DEP_DAG         
        FOREIGN KEY (DAG_ID)
        REFERENCES PI_FLOW.METADATA.DAG(DAG_ID)
);


CREATE OR REPLACE TABLE PI_FLOW.METADATA.XCOM (
    ID NUMBER AUTOINCREMENT,
    DAG_ID VARCHAR NOT NULL,
    TASK_ID VARCHAR NOT NULL,
    RUN_ID VARCHAR NOT NULL,
    KEY VARCHAR NOT NULL,
    VALUE VARIANT,  -- Snowflake JSON type
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);








