use pi_flow.metadata;

delete from task_dependency where id=201;

delete from task where id=104;

select * from task;

select * from task_dependency;

CREATE OR REPLACE TABLE PI_FLOW.METADATA.TASK (
    ID NUMBER(38,0)
        AUTOINCREMENT START 1000 INCREMENT 1 NOORDER,
    DAG_ID VARCHAR NOT NULL,
    TASK_ID VARCHAR NOT NULL,
    OPERATOR VARCHAR,
    OWNER VARCHAR,
    DESCRIPTION VARCHAR,
    RETRIES NUMBER DEFAULT 0,
    RETRY_DELAY_SECONDS NUMBER,
    PARAMS VARIANT,
    CONSTRAINT UK_TASK UNIQUE (DAG_ID, TASK_ID),
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_DAG
        FOREIGN KEY (DAG_ID)
        REFERENCES PI_FLOW.METADATA.DAG(DAG_ID)
);

CREATE OR REPLACE TABLE PI_FLOW.METADATA.TASK_DEPENDENCY (
    ID NUMBER(38,0)
        AUTOINCREMENT START 1000 INCREMENT 1 NOORDER,
    DAG_ID VARCHAR NOT NULL,
    UPSTREAM_TASK_ID VARCHAR NOT NULL,
    DOWNSTREAM_TASK_ID VARCHAR NOT NULL,
    CONSTRAINT UK_TASK_DEP
        UNIQUE (DAG_ID, UPSTREAM_TASK_ID, DOWNSTREAM_TASK_ID),
    PRIMARY KEY (ID),
    CONSTRAINT FK_DEP_DAG         
        FOREIGN KEY (DAG_ID)
        REFERENCES PI_FLOW.METADATA.DAG(DAG_ID)
);

select current_user();

